import { Step } from 'react-joyride';

export const driverTour: Step[] = [
  {
    target: 'body',
    title: 'Welcome to Stalight Driver Portal!',
    content: 'Let\'s guide you through the Driver portal to manage your daily routes, start trips, and mark student attendance.',
    placement: 'center' as const,
    disableBeacon: true,
  },
  {
    target: '#sidebar-dashboard',
    title: 'Assigned Route & Details',
    content: 'Here you can view your Assigned Route, Assigned Bus details, Morning & Evening Start times, and Bus Capacity.',
    placement: 'bottom' as const,
    disableBeacon: true,
    route: '/driver',
  },
  {
    target: '#driver-trip-controls',
    title: "Start Today's Trip",
    content: 'Start morning or evening trips here to begin boarding and enable live tracking.',
    placement: 'bottom' as const,
    disableBeacon: true,
    route: '/driver',
  },
  {
    target: '#sidebar-driver-history',
    title: 'Trip History',
    content: 'Access and review historical trip attendance records, total boarding stats, and passenger logs.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/driver-history',
  },
  {
    target: '#sidebar-announcements',
    title: 'Announcements',
    content: 'View important announcements and updates broadcasted by campus transport management.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/announcements',
  },
  {
    target: '#sidebar-driver-complaints',
    title: 'Complaints',
    content: 'View and log complaints or vehicle breakdown incidents during transport routes.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/driver-complaints',
  },
  {
    target: '#sidebar-apply-leave',
    title: 'Apply Leave',
    content: 'Submit leave applications and track your request history.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/apply-leave',
  },
  {
    target: '#sidebar-my-attendance',
    title: 'My Attendance',
    content: 'Check your daily attendance logs and duty records.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/my-attendance',
  },
  {
    target: '#sidebar-holiday-calendar',
    title: 'Calendar',
    content: 'View institutional holiday calendar and scheduled events.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/holiday-calendar',
  },
  {
    target: '#sidebar-reimbursements',
    title: 'Reimbursements & Claims',
    content: 'Submit and monitor status of fuel or expense reimbursement claims.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/reimbursements',
  },
  {
    target: '#sidebar-my-payroll',
    title: 'My Salary & Payroll',
    content: 'View your monthly salary statements, pay slips, and statutory deductions.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/my-payroll',
  },
  {
    target: '#sidebar-profile',
    title: 'Profile Settings',
    content: 'Manage your driver account details, security credentials, and preferences.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/driver/profile',
  },
];
