import { Step } from 'react-joyride';

export const orgAdminTour: Step[] = [
  {
    target: 'body',
    title: 'Welcome, Organization Admin!',
    content:
      'Let\'s take a quick tour to guide you through managing your institution, users, enrollments, and billing settings.',
    placement: 'center' as const,
    disableBeacon: true,
  },
  {
    target: '#admin-stats-grid',
    title: 'System Statistics',
    content:
      'Monitor overall institutional counts such as active branches, total students, faculty, and principals.',
    placement: 'bottom' as const,
    disableBeacon: true,
    route: '/org-admin',
  },
  {
    target: '#admission-overview-grid',
    title: 'Admission Overview',
    content:
      'Track total admissions enquiries, application forms submitted, seats allocated, and enrolled students at a glance.',
    placement: 'bottom' as const,
    disableBeacon: true,
    route: '/org-admin',
  },
  {
    target: '#branch-distribution-chart',
    title: 'Branch Distribution',
    content:
      'Analyze the count of students and faculty members\ndistributed across various branches using the bar chart.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin',
  },
  {
    target: '#role-distribution-chart',
    title: 'Role Distribution',
    content:
      'Monitor the system user count distribution grouped by their roles using the pie chart.',
    placement: 'left' as const,
    disableBeacon: true,
    route: '/org-admin',
  },
  {
    target: '#branch-statistics-table',
    title: 'Branch Statistics',
    content:
      'View the detailed breakdown of student and faculty numbers for each branch.',
    placement: 'top' as const,
    disableBeacon: true,
    route: '/org-admin',
  },
  {
    target: '#admin-action-cards',
    title: 'Action Cards Console',
    content:
      'Quick shortcuts to:\n• Enroll User: Add new HOD or faculty\n• Bulk Upload Faculty: Upload faculty list\n• Manage Branches: View or edit branches\n• Faculty Assignments: Assign teachers to branches & subjects\n• Manage Batches: View or manage batches\n• Notifications: Send or view notifications\n• HOD Leaves: Manage HOD leave requests\n• Users Management: Manage all system users',
    placement: 'top' as const,
    disableBeacon: true,
    route: '/org-admin',
  },
  {
    target: '#sidebar-branches',
    title: 'Branch Management',
    content: 'View, edit, and configure all branches or departments in your institution.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/branches',
  },
  {
    target: '#sidebar-batches',
    title: 'Batches Management',
    content: 'Manage batches, academic sections, and cohort structures.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/batches',
  },
  {
    target: '#sidebar-faculty',
    title: 'Faculty Management',
    content: 'View and audit faculty listings, departments, and specific academic tasks.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/faculty',
  },
  {
    target: '#sidebar-users',
    title: 'Users Directory',
    content:
      'Search, filter, view, edit, or deactivate student, faculty, HOD, and staff profiles inside your organization.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/users',
  },
  {
    target: '#sidebar-enroll-user',
    title: 'Enroll Staff',
    content:
      'Enroll and onboard new institutional roles (HODs, faculty members, Deans, COE, or Fees Managers) easily.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/enroll-user',
  },
  {
    target: '#sidebar-attendance',
    title: "Today's Attendance",
    content: 'Monitor daily attendance summary, check present/absent ratios, and track leaves.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/attendance',
  },
  {
    target: '#sidebar-exams',
    title: 'Exams Portal',
    content: 'Oversight of examinations schedule, status, and pending approvals.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/exams',
  },
  {
    target: '#sidebar-finance',
    title: 'Finance Dashboard',
    content: 'Analyze high-level financial health, fee collection charts, and transaction trends.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/finance',
  },
  {
    target: '#sidebar-payments',
    title: 'Payments Log',
    content: 'Access all digital and offline transaction records.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/payments',
  },
  {
    target: '#sidebar-invoices',
    title: 'Invoices',
    content: 'Track and generate itemized student or branch invoices.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/invoices',
  },
  {
    target: '#sidebar-reports',
    title: 'Reports & Analytics',
    content: 'Generate consolidated academic, attendance, or finance reports.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/reports',
  },
  {
    target: '#sidebar-announcement-management',
    title: 'Announcements',
    content: 'Broadcast notifications and updates to all branches or specific targets.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/announcement-management',
  },
  {
    target: '#sidebar-schedule-meeting',
    title: 'Schedule Meetings',
    content: 'Plan, configure, and coordinate interactive meetings with HODs, faculty, or students.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/schedule-meeting',
  },
  {
    target: '#sidebar-campus-locations',
    title: 'Campus Locations',
    content: 'View and manage physical campus buildings, rooms, locations, and facilities.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/campus-locations',
  },
  {
    target: '#sidebar-billing',
    title: 'Billing & Plans',
    content:
      'View your active plan details, organization administrative metadata, technical POC details, invoice receipt history, and raise support tickets.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/billing',
  },
  {
    target: '#sidebar-scan-student-info',
    title: 'Scan Student Info',
    content: 'Quickly scan or search for student information across the organization.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/scan-student-info',
  },
  {
    target: '#sidebar-alumni-directory',
    title: 'Alumni Directory',
    content: 'Track and stay connected with graduated cohorts and manage alumni relations.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/alumni-directory',
  },
  {
    target: '#sidebar-staff-tasks',
    title: 'Staff Tasks',
    content: 'Assign tasks, monitor execution progress, and track daily administration workflows.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/staff-tasks',
  },
  {
    target: '#sidebar-holiday-calendar',
    title: 'Academic & Holiday Calendar',
    content: 'Check the official academic schedule, view scheduled holidays, and track upcoming institutional milestones.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/holiday-calendar',
  },
  {
    target: '#sidebar-my-payroll',
    title: 'Payroll & Salary Logs',
    content: 'View monthly payroll statistics, check salary statements, and monitor transaction receipts.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/my-payroll',
  },
  {
    target: '#sidebar-profile',
    title: 'Profile Settings',
    content:
      'Manage your personal admin profile settings, security credentials, and preferences.',
    placement: 'right' as const,
    disableBeacon: true,
    route: '/org-admin/profile',
  },
];
