from .views import hod_views, admin_views, profile_views, assignment_views, exam_views, report_views
from .views.hod import *
from .views.admin import *
from .views import hod_views, student_views, admin_views, faculty_views, profile_views, assignment_views, exam_views, report_views, hod2_views, faculty2_views, faculty3_views, faculty3_endpoints
from .views import fees_manager_views
from .views import coe
from .views import coe_views
from .views import revalv_views
from .views.coe import (
from .views.coe_views import (
    dashboard_stats,
    exam_applications,
    action_exam_application,
@@ -21,32 +19,30 @@
    get_published_results,
    public_view_result_by_token,
    StudentApplicationStatusView,
    CourseApplicationStatsView,
    export_not_applied,
    CourseApplicationStatsView
    ,export_not_applied,
    export_not_applied_debug
)
from .views.ai import student_ai_chatbot
from .views.ai import ai_campus_assistant, get_faculty_profile
from .views.student_ai_chatbot import student_ai_chatbot
from .views.faculty_ai_chatbot import ai_campus_assistant, get_faculty_profile
from rest_framework_simplejwt.views import TokenRefreshView
from . import views
from .views import run_migrations_view
from .views.ai import PDFUploadView, AskQuestionView
from .views.pdf_views import PDFUploadView, AskQuestionView
from .stripe_views import CreateCheckoutSessionView, InvoiceComponentSelectionView, ComponentBasedPaymentView, PaymentStatusView, StripeWebhookView, RefundPaymentView
from .views.coe.attainment import co_attainment
from .views.faculty import *
from .views.student import *
from .views.co_attainment import co_attainment

app_name = 'api'

urlpatterns = [
    # Authentication endpoints - handle both with/without trailing slash
    re_path(r'^login/?$', login_view, name='login'),
    re_path(r'^forgot-password/?$', forgot_password, name='forgot_password'),
    re_path(r'^verify-otp/?$', verify_otp, name='verify_otp'),
    re_path(r'^resend-otp/?$', resend_otp, name='resend_otp'),
    re_path(r'^reset-password/?$', reset_password, name='reset_password'),
    re_path(r'^login/?$', student_views.login_view, name='login'),
    re_path(r'^forgot-password/?$', student_views.forgot_password, name='forgot_password'),
    re_path(r'^verify-otp/?$', student_views.verify_otp, name='verify_otp'),
    re_path(r'^resend-otp/?$', student_views.resend_otp, name='resend_otp'),
    re_path(r'^reset-password/?$', student_views.reset_password, name='reset_password'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', logout, name='logout'),
    path('logout/', student_views.logout, name='logout'),

    # Profile Management endpoints
    path('profile/', profile_views.manage_profile, name='manage_profile'),
@@ -55,90 +51,90 @@
    path('profile/stats/', profile_views.get_user_stats, name='get_user_stats'),

    # Student endpoints
    path('student/dashboard/', dashboard_overview, name='student_dashboard'),
    path('student/dashboard-with-notifications/', get_dashboard_with_notifications, name='student_dashboard_with_notifications'),
    path('student/timetable/', get_timetable, name='get_student_timetable'),
    path('student/attendance/', get_student_attendance, name='get_student_attendance'),
    path('student/attendance-with-marks/', get_attendance_with_marks, name='get_attendance_with_marks'),
    path('student/internal-marks/', get_internal_marks, name='get_student_internal_marks'),
    path('student/submit-leave-request/', submit_student_leave_request, name='submit_student_leave_request'),
    path('student/leave-requests/', get_student_leave_requests, name='get_student_leave_requests'),
    path('student/upload-certificate/', upload_certificate, name='upload_certificate'),
    path('student/bulk-upload-certificates/', bulk_upload_certificates, name='bulk_upload_certificates'),
    path('student/certificates/', get_certificates, name='get_certificates'),
    path('student/delete-certificate/', delete_certificate, name='delete_certificate'),
    path('student/update-profile/', update_profile, name='update_profile'),
    path('student/chat/', manage_chat, name='student_chat'),
    path('student/notifications/', get_notifications, name='get_student_notifications'),
    path('student/announcements/', get_announcements, name='get_student_announcements'),
    path('student/full-profile/', get_full_student_profile, name='get_full_student_profile'),
    path('student/study-materials/', get_study_materials, name='get_study_materials'),
    path('student/assignments/', get_student_assignments, name='get_student_assignments'),
    path('student/historical-data/', get_historical_student_data, name='get_historical_student_data'),
    path('student/dashboard/', student_views.dashboard_overview, name='student_dashboard'),
    path('student/dashboard-with-notifications/', student_views.get_dashboard_with_notifications, name='student_dashboard_with_notifications'),
    path('student/timetable/', student_views.get_timetable, name='get_student_timetable'),
    path('student/attendance/', student_views.get_student_attendance, name='get_student_attendance'),
    path('student/attendance-with-marks/', student_views.get_attendance_with_marks, name='get_attendance_with_marks'),
    path('student/internal-marks/', student_views.get_internal_marks, name='get_student_internal_marks'),
    path('student/submit-leave-request/', student_views.submit_student_leave_request, name='submit_student_leave_request'),
    path('student/leave-requests/', student_views.get_student_leave_requests, name='get_student_leave_requests'),
    path('student/upload-certificate/', student_views.upload_certificate, name='upload_certificate'),
    path('student/bulk-upload-certificates/', student_views.bulk_upload_certificates, name='bulk_upload_certificates'),
    path('student/certificates/', student_views.get_certificates, name='get_certificates'),
    path('student/delete-certificate/', student_views.delete_certificate, name='delete_certificate'),
    path('student/update-profile/', student_views.update_profile, name='update_profile'),
    path('student/chat/', student_views.manage_chat, name='student_chat'),
    path('student/notifications/', student_views.get_notifications, name='get_student_notifications'),
    path('student/announcements/', student_views.get_announcements, name='get_student_announcements'),
    path('student/full-profile/', student_views.get_full_student_profile, name='get_full_student_profile'),
    path('student/study-materials/', student_views.get_study_materials, name='get_study_materials'),
    path('student/assignments/', student_views.get_student_assignments, name='get_student_assignments'),
    path('student/historical-data/', student_views.get_historical_student_data, name='get_historical_student_data'),
    path('student/exams/', exam_views.get_student_exams, name='get_student_exams'),
    path('student/fee-data/', get_student_fee_data, name='get_student_fee_data'),
    path('student/fee-data/', student_views.get_student_fee_data, name='get_student_fee_data'),
    path('ai-chatbot/', student_ai_chatbot, name='ai_chatbot'),
    path('student/ai-chatbot/', student_ai_chatbot, name='student_ai_chatbot'),

    # Face Recognition endpoints
    path('student/train-face/', train_face, name='train_face'),
    path('student/check-face-status/', check_face_status, name='check_face_status'),
    path('recognize-face/', recognize_face, name='recognize_face'),
    path('student/train-face/', student_views.train_face, name='train_face'),
    path('student/check-face-status/', student_views.check_face_status, name='check_face_status'),
    path('recognize-face/', student_views.recognize_face, name='recognize_face'),

    # Public API endpoint for student data by USN
    path('public/student-data/', get_student_data_by_usn, name='get_student_data_by_usn'),
    path('common/subjects/', get_subjects_for_branch_semester, name='common_subjects'),
    path('common/subject-detail/', get_subject_detail, name='common_subject_detail'),
    path('public/student-data/', student_views.get_student_data_by_usn, name='get_student_data_by_usn'),
    path('common/subjects/', student_views.get_subjects_for_branch_semester, name='common_subjects'),
    path('common/subject-detail/', student_views.get_subject_detail, name='common_subject_detail'),

    # Faculty endpoints
    path('faculty/dashboard/', dashboard_overview, name='faculty_dashboard'),
    path('faculty/dashboard/bootstrap/', faculty_dashboard_bootstrap, name='faculty_dashboard_bootstrap'),
    path('faculty/attendance-records/summary/', get_attendance_records_with_summary, name='get_attendance_records_with_summary'),
    path('faculty/apply-leave/bootstrap/', get_apply_leave_bootstrap, name='get_apply_leave_bootstrap'),
    path('faculty/take-attendance/bootstrap/', get_take_attendance_bootstrap, name='get_take_attendance_bootstrap'),
    path('faculty/assigned-subjects/', get_assigned_subjects, name='get_assigned_subjects'),
    path('faculty/students/regular/', get_students_regular, name='get_students_regular'),
    path('faculty/students/elective/', get_students_elective, name='get_students_elective'),
    path('faculty/students/open-elective/', get_students_open_elective, name='get_students_open_elective'),
    path('faculty/upload-marks/bootstrap/', get_upload_marks_bootstrap, name='get_upload_marks_bootstrap'),
    path('faculty/take-attendance/', take_attendance, name='take_attendance'),
    path('faculty/ai-attendance/', ai_attendance, name='ai_attendance'),
    path('faculty/upload-marks/', upload_internal_marks, name='upload_internal_marks'),
    path('faculty/qps/', question_paper_list_create, name='question_paper_list_create'),
    path('faculty/qps/<int:qp_id>/', update_question_paper, name='update_question_paper'),
    path('faculty/students-for-marks/', get_students_for_marks, name='get_students_for_marks'),
    path('faculty/upload-ia-marks/', upload_ia_marks, name='upload_ia_marks'),
    path('faculty/apply-leave/', apply_leave, name='apply_leave'),
    path('faculty/leave-requests/', get_faculty_leave_requests, name='get_faculty_leave_requests'),
    path('faculty/attendance-records/', view_attendance_records, name='view_attendance_records'),
    path('faculty/attendance-records/list/', get_attendance_records_list, name='get_attendance_records_list'),
    path('faculty/attendance-records/<int:record_id>/details/', attendance_record_details, name='attendance_record_details'),
    path('faculty/announcements/', create_announcement, name='create_announcement'),
    path('faculty/proctor-students/', get_proctor_students, name='get_proctor_students'),
    path('faculty/manage-student-leave/', manage_student_leave, name='manage_student_leave'),
    path('faculty/assignments/', get_faculty_assignments, name='get_faculty_assignments'),
    path('faculty/timetable/', get_timetable, name='get_faculty_timetable'),
    path('faculty/chat/', manage_chat, name='manage_chat'),
    path('faculty/profile/', manage_profile, name='manage_profile'),
    path('faculty/schedule-mentoring/', schedule_mentoring, name='schedule_mentoring'),
    path('faculty/generate-statistics/', generate_statistics, name='generate_statistics'),
    path('faculty/download-pdf/<str:filename>/', download_pdf, name='download_pdf'),
    path('faculty/students/', get_students_for_class, name='get_students_for_class'),
    path('faculty/internal-marks/', get_internal_marks_for_class, name='get_internal_marks_for_class'),
    path('faculty/notifications/', get_notifications, name='get_faculty_notifications'),
    path('faculty/notifications/sent/', get_sent_notifications, name='get_faculty_sent_notifications'),
    path('faculty/dashboard/', faculty_views.dashboard_overview, name='faculty_dashboard'),
    path('faculty/dashboard/bootstrap/', faculty2_views.faculty_dashboard_bootstrap, name='faculty_dashboard_bootstrap'),
    path('faculty/attendance-records/summary/', faculty2_views.get_attendance_records_with_summary, name='get_attendance_records_with_summary'),
    path('faculty/apply-leave/bootstrap/', faculty2_views.get_apply_leave_bootstrap, name='get_apply_leave_bootstrap'),
    path('faculty/take-attendance/bootstrap/', faculty2_views.get_take_attendance_bootstrap, name='get_take_attendance_bootstrap'),
    path('faculty/assigned-subjects/', faculty2_views.get_assigned_subjects, name='get_assigned_subjects'),
    path('faculty/students/regular/', faculty2_views.get_students_regular, name='get_students_regular'),
    path('faculty/students/elective/', faculty2_views.get_students_elective, name='get_students_elective'),
    path('faculty/students/open-elective/', faculty2_views.get_students_open_elective, name='get_students_open_elective'),
    path('faculty/upload-marks/bootstrap/', faculty2_views.get_upload_marks_bootstrap, name='get_upload_marks_bootstrap'),
    path('faculty/take-attendance/', faculty_views.take_attendance, name='take_attendance'),
    path('faculty/ai-attendance/', faculty3_views.ai_attendance, name='ai_attendance'),
    path('faculty/upload-marks/', faculty_views.upload_internal_marks, name='upload_internal_marks'),
    path('faculty/qps/', faculty_views.question_paper_list_create, name='question_paper_list_create'),
    path('faculty/qps/<int:qp_id>/', faculty_views.update_question_paper, name='update_question_paper'),
    path('faculty/students-for-marks/', faculty_views.get_students_for_marks, name='get_students_for_marks'),
    path('faculty/upload-ia-marks/', faculty_views.upload_ia_marks, name='upload_ia_marks'),
    path('faculty/apply-leave/', faculty_views.apply_leave, name='apply_leave'),
    path('faculty/leave-requests/', faculty_views.get_faculty_leave_requests, name='get_faculty_leave_requests'),
    path('faculty/attendance-records/', faculty_views.view_attendance_records, name='view_attendance_records'),
    path('faculty/attendance-records/list/', faculty_views.get_attendance_records_list, name='get_attendance_records_list'),
    path('faculty/attendance-records/<int:record_id>/details/', faculty_views.attendance_record_details, name='attendance_record_details'),
    path('faculty/announcements/', faculty_views.create_announcement, name='create_announcement'),
    path('faculty/proctor-students/', faculty_views.get_proctor_students, name='get_proctor_students'),
    path('faculty/manage-student-leave/', faculty_views.manage_student_leave, name='manage_student_leave'),
    path('faculty/assignments/', faculty_views.get_faculty_assignments, name='get_faculty_assignments'),
    path('faculty/timetable/', faculty_views.get_timetable, name='get_faculty_timetable'),
    path('faculty/chat/', faculty_views.manage_chat, name='manage_chat'),
    path('faculty/profile/', faculty_views.manage_profile, name='manage_profile'),
    path('faculty/schedule-mentoring/', faculty_views.schedule_mentoring, name='schedule_mentoring'),
    path('faculty/generate-statistics/', faculty_views.generate_statistics, name='generate_statistics'),
    path('faculty/download-pdf/<str:filename>/', faculty_views.download_pdf, name='download_pdf'),
    path('faculty/students/', faculty_views.get_students_for_class, name='get_students_for_class'),
    path('faculty/internal-marks/', faculty_views.get_internal_marks_for_class, name='get_internal_marks_for_class'),
    path('faculty/notifications/', faculty_views.get_notifications, name='get_faculty_notifications'),
    path('faculty/notifications/sent/', faculty_views.get_sent_notifications, name='get_faculty_sent_notifications'),
    path('faculty/ai-campus-assistant/', ai_campus_assistant, name='ai_campus_assistant'),
    path('faculty/ai-campus-assistant/profile/', get_faculty_profile, name='ai_campus_assistant_profile'),
    path('faculty/mark-attendance/', mark_faculty_attendance, name='mark_faculty_attendance'),
    path('faculty/my-attendance-records/', get_faculty_attendance_records, name='get_faculty_attendance_records'),
    path('faculty/mark-attendance/', faculty_views.mark_faculty_attendance, name='mark_faculty_attendance'),
    path('faculty/my-attendance-records/', faculty_views.get_faculty_attendance_records, name='get_faculty_attendance_records'),

    # Exam Application endpoints
    path('faculty/exam-applications/', exam_applications, name='exam_applications'),
    path('faculty/hall-ticket/<int:student_id>/', download_hall_ticket, name='download_hall_ticket'),
    path('faculty/proctor-students/exam-status/', proctor_students_exam_status, name='proctor_students_exam_status'),
    path('faculty/exam-applications/', faculty_views.exam_applications, name='exam_applications'),
    path('faculty/hall-ticket/<int:student_id>/', faculty_views.download_hall_ticket, name='download_hall_ticket'),
    path('faculty/proctor-students/exam-status/', faculty_views.proctor_students_exam_status, name='proctor_students_exam_status'),
    # Consolidated endpoint that returns proctor students enriched with exam status when exam_period is provided
    path('faculty/proctor-students/with-exam-status/', proctor_students_with_exam_status, name='proctor_students_with_exam_status'),
    path('faculty/exam-student-subjects/', exam_student_subjects, name='exam_student_subjects'),
    path('faculty/proctor-students/with-exam-status/', faculty3_endpoints.proctor_students_with_exam_status, name='proctor_students_with_exam_status'),
    path('faculty/exam-student-subjects/', faculty3_views.exam_student_subjects, name='exam_student_subjects'),

    # Assignment Management endpoints
    path('faculty/assignments/manage/', assignment_views.manage_assignments, name='manage_assignments'),
@@ -164,25 +160,25 @@
    path('co-attainment/', co_attainment, name='co_attainment'),

    # HOD endpoints
    path('hod/dashboard/', hod_dashboard_bootstrap, name='hod_dashboard'),
    path('hod/bootstrap/', hod_bootstrap, name='hod_bootstrap'),
    path('hod/student-bootstrap/', hod_student_bootstrap, name='hod_student_bootstrap'),
    path('hod/subject-bootstrap/', hod_subjects_bootstrap, name='hod_subjects_bootstrap'),
    path('hod/timetable-bootstrap/', hod_timetable_bootstrap, name='hod_timetable_bootstrap'),
    path('hod/timetable-semester-data/', hod_timetable_semester_data, name='hod_timetable_semester_data'),
    path('hod/attendance-bootstrap/', hod_attendance_bootstrap, name='hod_attendance_bootstrap'),
    path('hod/leave-bootstrap/', hod_leave_bootstrap, name='hod_leave_bootstrap'),
    path('hod/faculty-leaves-bootstrap/', hod_faculty_leaves_bootstrap, name='hod_faculty_leaves_bootstrap'),
    path('hod/proctor-bootstrap/', hod_proctor_bootstrap, name='hod_proctor_bootstrap'),
    path('hod/semester-bootstrap/', hod_semester_bootstrap, name='hod_semester_bootstrap'),
    path('hod/marks-bootstrap/', hod_marks_bootstrap, name='hod_marks_bootstrap'),
    path('hod/faculty-assignments-bootstrap/', hod_faculty_assignments_bootstrap, name='hod_faculty_assignments_bootstrap'),
    path('hod/promotion-bootstrap/', hod_promotion_bootstrap, name='hod_promotion_bootstrap'),
    path('hod/low-attendance-bootstrap/', hod_low_attendance_bootstrap, name='hod_low_attendance_bootstrap'),
    path('hod/low-attendance-students/', hod_low_attendance_students, name='hod_low_attendance_students'),
    path('hod/elective-enrollment-bootstrap/', hod_elective_enrollment_bootstrap, name='hod_elective_enrollment_bootstrap'),
    path('hod/dashboard-stats/', dashboard_stats, name='hod_stats'),
    path('hod/low-attendance/', low_attendance_students, name='hod_low_attendance'),
    path('hod/dashboard/', hod2_views.hod_dashboard_bootstrap, name='hod_dashboard'),
    path('hod/bootstrap/', hod2_views.hod_bootstrap, name='hod_bootstrap'),
    path('hod/student-bootstrap/', hod2_views.hod_student_bootstrap, name='hod_student_bootstrap'),
    path('hod/subject-bootstrap/', hod2_views.hod_subjects_bootstrap, name='hod_subjects_bootstrap'),
    path('hod/timetable-bootstrap/', hod2_views.hod_timetable_bootstrap, name='hod_timetable_bootstrap'),
    path('hod/timetable-semester-data/', hod2_views.hod_timetable_semester_data, name='hod_timetable_semester_data'),
    path('hod/attendance-bootstrap/', hod2_views.hod_attendance_bootstrap, name='hod_attendance_bootstrap'),
    path('hod/leave-bootstrap/', hod2_views.hod_leave_bootstrap, name='hod_leave_bootstrap'),
    path('hod/faculty-leaves-bootstrap/', hod2_views.hod_faculty_leaves_bootstrap, name='hod_faculty_leaves_bootstrap'),
    path('hod/proctor-bootstrap/', hod2_views.hod_proctor_bootstrap, name='hod_proctor_bootstrap'),
    path('hod/semester-bootstrap/', hod2_views.hod_semester_bootstrap, name='hod_semester_bootstrap'),
    path('hod/marks-bootstrap/', hod2_views.hod_marks_bootstrap, name='hod_marks_bootstrap'),
    path('hod/faculty-assignments-bootstrap/', hod2_views.hod_faculty_assignments_bootstrap, name='hod_faculty_assignments_bootstrap'),
    path('hod/promotion-bootstrap/', hod2_views.hod_promotion_bootstrap, name='hod_promotion_bootstrap'),
    path('hod/low-attendance-bootstrap/', hod2_views.hod_low_attendance_bootstrap, name='hod_low_attendance_bootstrap'),
    path('hod/low-attendance-students/', hod2_views.hod_low_attendance_students, name='hod_low_attendance_students'),
    path('hod/elective-enrollment-bootstrap/', hod2_views.hod_elective_enrollment_bootstrap, name='hod_elective_enrollment_bootstrap'),
    path('hod/dashboard-stats/', hod_views.dashboard_stats, name='hod_stats'),
    path('hod/low-attendance/', hod_views.low_attendance_students, name='hod_low_attendance'),
    path('hod/semesters/', hod_views.manage_semesters, name='hod_semesters'),
    path('hod/sections/', hod_views.manage_sections, name='hod_sections'),
    path('hod/students/', hod_views.manage_students, name='hod_manage_students'),
@@ -219,29 +215,29 @@
    path('hod/demote-students/bulk/', hod_views.bulk_demote_students, name='bulk_demote_students'),

    # Admin endpoints
    path('admin/stats-overview/', stats_overview, name='admin_stats_overview'),
    path('admin/enroll-user/', enroll_user, name='admin_enroll_user'),
    path('admin/bulk-upload-faculty/', bulk_upload_faculty, name='admin_bulk_upload_faculty'),
    path('admin/branches/', manage_branches, name='admin_manage_branches'),
    path('admin/branches/<int:branch_id>/', manage_branches, name='admin_manage_branch'),
    path('admin/branches-with-hods/', get_branches_with_hods, name='admin_branches_with_hods'),
    path('admin/batches/', manage_batches, name='admin_manage_batches'),
    path('admin/batches/<int:batch_id>/', manage_batches, name='admin_manage_batch'),
    path('admin/notifications/', manage_notifications, name='admin_manage_notifications'),
    path('admin/hod-leaves/', manage_hod_leaves, name='admin_manage_hod_leaves'),
    path('admin/hod-leaves/bulk-process/', bulk_process_hod_leaves, name='admin_bulk_process_hod_leaves'),
    path('admin/users/', user_directory, name='admin_user_directory'),
    path('admin/users/bulk-actions/', bulk_user_actions, name='admin_bulk_user_actions'),
    path('admin/profile/<int:user_id>/', manageAdminProfile, name='admin_profile_management'),
    path('admin/campus-locations/', manage_campus_location, name='admin_manage_campus_locations'),
    path('admin/campus-locations/<int:location_id>/', manage_campus_location, name='admin_manage_campus_location'),
    path('admin/stats-overview/', admin_views.stats_overview, name='admin_stats_overview'),
    path('admin/enroll-user/', admin_views.enroll_user, name='admin_enroll_user'),
    path('admin/bulk-upload-faculty/', admin_views.bulk_upload_faculty, name='admin_bulk_upload_faculty'),
    path('admin/branches/', admin_views.manage_branches, name='admin_manage_branches'),
    path('admin/branches/<int:branch_id>/', admin_views.manage_branches, name='admin_manage_branch'),
    path('admin/branches-with-hods/', admin_views.get_branches_with_hods, name='admin_branches_with_hods'),
    path('admin/batches/', admin_views.manage_batches, name='admin_manage_batches'),
    path('admin/batches/<int:batch_id>/', admin_views.manage_batches, name='admin_manage_batch'),
    path('admin/notifications/', admin_views.manage_notifications, name='admin_manage_notifications'),
    path('admin/hod-leaves/', admin_views.manage_hod_leaves, name='admin_manage_hod_leaves'),
    path('admin/hod-leaves/bulk-process/', admin_views.bulk_process_hod_leaves, name='admin_bulk_process_hod_leaves'),
    path('admin/users/', admin_views.user_directory, name='admin_user_directory'),
    path('admin/users/bulk-actions/', admin_views.bulk_user_actions, name='admin_bulk_user_actions'),
    path('admin/profile/<int:user_id>/', admin_views.manageAdminProfile, name='admin_profile_management'),
    path('admin/campus-locations/', admin_views.manage_campus_location, name='admin_manage_campus_locations'),
    path('admin/campus-locations/<int:location_id>/', admin_views.manage_campus_location, name='admin_manage_campus_location'),

    # Teacher-Branch Assignment endpoints
    path('admin/teacher-assignments/', get_teacher_branch_assignments, name='admin_teacher_assignments'),
    path('admin/assign-teacher-branch/', assign_teacher_to_branch, name='admin_assign_teacher_branch'),
    path('admin/assign-teacher-subject/', assign_teacher_to_subject, name='admin_assign_teacher_subject'),
    path('admin/remove-teacher-assignment/<int:assignment_id>/', remove_teacher_assignment, name='admin_remove_teacher_assignment'),
    path('admin/assignment-options/', get_assignment_options, name='admin_assignment_options'),
    path('admin/teacher-assignments/', admin_views.get_teacher_branch_assignments, name='admin_teacher_assignments'),
    path('admin/assign-teacher-branch/', admin_views.assign_teacher_to_branch, name='admin_assign_teacher_branch'),
    path('admin/assign-teacher-subject/', admin_views.assign_teacher_to_subject, name='admin_assign_teacher_subject'),
    path('admin/remove-teacher-assignment/<int:assignment_id>/', admin_views.remove_teacher_assignment, name='admin_remove_teacher_assignment'),
    path('admin/assignment-options/', admin_views.get_assignment_options, name='admin_assignment_options'),

    # Fees Manager endpoints
    path('fees-manager/dashboard/', fees_manager_views.fees_manager_dashboard, name='fees_manager_dashboard'),
